### PR TITLE
create TODO app as an example

### PR DESCRIPTION
**Pull request by ivanhofer**
The basic functionality was implemented.

@NilsJacobsen it is your turn to add some CSS to make the application more appealing.

Feel free to change any texts or add new ones.

### CODE REVIEW

**Review by NilsJacobsen — APPROVED** [review]

**Comment by NilsJacobsen** [comment]
@ivanhofer looks good to me

**Comment by NilsJacobsen** [comment]
@ivanhofer can we merge?

**Comment by ivanhofer** [comment]
Some feedback:
 - "docs" is a link and should be visually distingushed from the regular text
   image
 - those are two sentences so they should probably be split into two lines

**Comment by NilsJacobsen** [comment]
image

**Pull request merged**
