### PR TITLE
add sveltekit to example

### PR DESCRIPTION
**Pull request by felixhaeberle**
this adds a basic sveltekit examples for further testing the functionality of the ide-extension and the editor.

### CODE REVIEW

**Comment by samuelstroschein** [comment]
do we need a full blown example with playwright etc? 

i would assume that the most minimal example imaginable helps developers better how inlang works with sveltekit.

**Comment by samuelstroschein** [comment]
we all love typescript don't we? yeah typescript seems reasonable

**Comment by felixhaeberle** [comment]
@samuelstroschein I'm on it!

**Comment by samuelstroschein** [comment]
@felixhaeberle merge yourself. i only see myself required for reviews that touch on @inlang/core

**Pull request merged**
