### PR TITLE
feat: truncate message preview

### PR DESCRIPTION
**Pull request by openscript**

### CODE REVIEW

**Comment by openscript** [comment]
Line breaks aren't possible for `contentText`. Here are my thoughts:
- A quick preview is a very handy feature, which should be as accessible as possible.
- Probably we will have other customization (color disability, ...) or some want to disable the preview entirely (accessibility).
- There is a tooltip on the message reference which shows the full translation.
- Tooltips are hard to consume, when you only what to use the keyboard.
- If we remove the setting, it won't cause a breaking change, because it is now optional.

**Comment by openscript** [comment]
ping @samuelstroschein

**Comment by samuelstroschein** [comment]
I vote for not enabling this feature now and wait for feedback from users.

**Comment by openscript** [comment]
Sound good to me.

**Pull request closed without merging**
